### ISSUE TITLE
Support for Coinigy API

### ISSUE THREAD

**Issue by m-roberts** [saniales/golang-crypto-trading-bot#10]
http://docs.coinigy.apiary.io/
This will allow the bot to work with many exchanges with only a single interface. The title is very self-explanatory - take their 30 day trial and see if you like what you can do with it.

**Comment by saniales** [comment]
provide a description, please.

**Comment by m-roberts** [comment]
http://docs.coinigy.apiary.io/
This will allow the bot to work with many exchanges with only a single interface.  The title is very self-explanatory - take their 30 day trial and see if you like what you can do with it.

**Comment by saniales** [comment]
thank you
