### ISSUE TITLE
Cannot add tactic: Strategy Watch5Sec does not exist

### ISSUE THREAD

**Issue by jameswellsiv** [saniales/golang-crypto-trading-bot#110]
Hello, 

I am using the .bot_config.yaml.example for my configuration. I have renamed the `-strategy` field in this yaml to `Watch5Sec` and I am receiving the error:

`Cannot add tactic: Strategy Watch5Sec does not exist` Do I need to do anything in the main.go file of my project in order for this Strategy to be seen?

**Comment by saniales** [comment]
hello @jameswellsiv 

you have to add the strategy as custom strategy following the example in the README

**Comment by jameswellsiv** [comment]
Okay, I did follow that example, and I got the error:

Undefined: AddCustomStrategy

I am not sure why it is not finding that function. The cmd and examples package are imported in my main.go!

**Comment by saniales** [comment]
Can you share a code snippet of your main.go file?

**Comment by jameswellsiv** [comment]
Yeah,

This is my main.go
`package main

import (
	bot "github.com/saniales/golang-crypto-trading-bot/cmd"
	"github.com/saniales/golang-crypto-trading-bot/examples"
	// "github.com/saniales/golang-crypto-trading-bot/strategies"
)

// import "github.com/saniales/golang-crypto-trading-bot/examples"

func main() {
	bot.AddCustomStrategy(examples.Watch5Sec)
	bot.Execute()
}
`

I forked this project, and just modified the main.go in the project to start.

I also tried to create a new go project, and imported this project into there and its not working because it does not support Go modules.

**Comment by saniales** [comment]
Have you tried disabling go modules or just having your project in GOPATH?

**Comment by vladblaj** [comment]
you need to add it as `strategies.AddCustomStrategy(examples.Websocket);` not `bot.AddCustomStrategy(examples.Watch5Sec)`

**Comment by saniales** [comment]
@vladblaj I think your comment resolves the same problem but for another strategy. i will keep it here but close the issue since it's solved ;)
