### ISSUE TITLE
Is there an example for implementing websocket example?

### ISSUE THREAD

**Issue by vladblaj** [saniales/golang-crypto-trading-bot#112]
Where exactly do I need to handle the update function? Do you simply do it in binance.go for example in subscribeMarketSummaryFeed?

**Comment by saniales** [comment]
check examples folder. I would say so

**Comment by vladblaj** [comment]
yea onUpdate works well for interval but not sure where to handle onUpdate in websockets cause it is not called. Do you simply add you logic in subscribeMarketSummaryFeed?

**Comment by vladblaj** [comment]
for example I would like to send to telegram using a websocket strategy when onUpdate is called. Cause onUpdate by websocket strategy I handled sending messages in subscribeMarketSummary but i don't think that is reasonable
![image](https://user-images.githubusercontent.com/5721913/150686799-9c6c4485-ca3f-49dc-807c-cd9945b0519d.png)

**Comment by saniales** [comment]
NO, that's the wrong way to resolve this ;)

from here

https://github.com/saniales/golang-crypto-trading-bot/blob/b0c20d4990023f4c81b9c4dee645ebff97f9cff0/strategies/websocket.go#L43-L46

So your setup function must call `FeedConnect()` to enable websockets, after that just Use the normal Update func

reference on why it works can be extracted from following lines

https://github.com/saniales/golang-crypto-trading-bot/blob/b0c20d4990023f4c81b9c4dee645ebff97f9cff0/exchanges/binance.go#L83-L100

Like from the example

https://github.com/saniales/golang-crypto-trading-bot/blob/develop/examples/websocket.go#L39-L42

**Comment by vladblaj** [comment]
Ok thanks, I tried again the websocket handler gets called for sure in binance.go. But after that I can not see how that is linked to the model onUpdate. It gets here: 
![image](https://user-images.githubusercontent.com/5721913/151002267-39c616bf-4b89-485e-9caf-75cc61cada2a.png)
But will never touch the onUpdate: 
![image](https://user-images.githubusercontent.com/5721913/151002347-91651e46-e9a9-4a23-a96e-7b9a99ea487e.png)

**Comment by vladblaj** [comment]
Indeed If I do it this way: 
![image](https://user-images.githubusercontent.com/5721913/151008988-e84eb02a-b953-48cb-b81a-9137b48fd5f3.png)
AND also call onUpdate in websocket it will work though it is not printed every second and again it does not seem right.

**Comment by saniales** [comment]
The fact that is not printed every second may depend on your internet connection. Can you double check that ?

Also try removing the go func()

**Comment by vladblaj** [comment]
I solved the issue using channels. It is not printed every second because it is printed hundred of times per second because of the non blocking for. Could you please show me for websocket strategy where exactly is the onUpdate called?.

**Comment by saniales** [comment]
The secret is the websocket part, the o update is run in the Apply method of Strategy implementation

It is complex to explain, but if you have websockets the population of wrapped structures is done on the fly by the subscribe functions.

**Comment by hmedkouri** [comment]
I think the question from @vladblaj is still valid.

@saniales  in websocket.go, what do you mean by "update is handled by the developer externally" in:

```
// update is handled by the developer externally, here we just checked for existence.
	if !hasUpdateFunc {
		_err := errors.New("OnUpdate func cannot be empty")
		if hasErrorFunc {
			wss.Model.OnError(_err)
		} else {
			panic(_err)
		}
	}
```

**Comment by VanoDevium** [comment]
I don't know about your solutions, but I broke my brain.

Just show a working example how to subscribe to changes in summaries and orderbook cache or where I have to put my own `for {}`.

Because all my attempts always end up the same way:
- no OnUpdate call
- the bot just says "bye"

Sorry, but there is no crystal clean (for understanding) example of ws strategy.

**Comment by saniales** [comment]
you have to pass the OnUpdate function as you would do without websockets, nothing changes, you just add the ws connection before initializing the bot
