### ISSUE TITLE
Invitation on developing golang based trading bot

### ISSUE THREAD

**Issue by zenixls2** [saniales/golang-crypto-trading-bot#118]
Hello @saniales , I've accidentally found this repo and seems you've already implemented several exchanges' connectivity that the other projects don't have.  

As a golang developer, I would like to invite you to help with another crypto trading bot also written in golang:  
https://github.com/c9s/bbgo

Also any pr been accepted will get project tokens in polygon chain (not much at this moment, also the pool in dex is still small).

Best regards,

**Comment by saniales** [comment]
Hey @zenixls2 I am sorry to disappoint you, but at the moment I will take full effort on developing my framework, maybe in the future we will join the efforts

Stay awesome 🚀
