### ISSUE TITLE
Why not integration with a Docker ?

### ISSUE THREAD

**Issue by kozld** [saniales/golang-crypto-trading-bot#121]
I think that it can maybe helpfully. What do you think?

**Comment by saniales** [comment]
Hello and thanks for asking

Are you thinking of a particular entry point integration or something generic would suit?

**Comment by saniales** [comment]
I thought about a generic Dockerized implementation

``` Dockerfile
FROM go:latest as builder
ADD .
RUN go build -o /tmp/golang-crypto-trading-bot 

FROM scratch

ADD config.yaml ./config.yaml
COPY --from=builder /tmp/golang-crypto-trading-bot ./golang-crypto-trading-bot 

CMD ["golang-crypto-trading-bot"]
```

that should do it (I did not test it) @kozld

**Comment by saniales** [comment]
After careful thinking about this, the manual Dockerfile is a better solution for anyone implementing any bot based on this framework, ergo I would keep any Docker version out of this repo.

If anybody needs to dockerize a project, can use the Dockerfile I provided in the other comment.
