### ISSUE TITLE
Test Strategy

### ISSUE THREAD

**Issue by alebeta90** [saniales/golang-crypto-trading-bot#92]
Hi,

I would like to know if there Watch5Sec strategy should work for default? I had been trying to configure it in my config for testing and it is not working, the bot says the strategy does not exist. Do I need to add my own in the code?

thanks in advance

**Comment by saniales** [comment]
Hello,
You need to add the custom strategy as the bot does not adds it by default.
Have in mind that all strategy implementations are just examples and must be treated as custom strategies

**Comment by ianeinser** [comment]
> Hello,
> You need to add the custom strategy as the bot does not adds it by default.
> Have in mind that all strategy implementations are just examples and must be treated as custom strategies

Hi,

sorry to reopen this again but how to add the strategy? i followed the example
    bot.AddCustomStrategy(examples.MyStrategy)

but it doesn't work. thanks in advance

**Comment by ianeinser** [comment]
Hi,

i solved it

it should be 

func main() {
	strategies.AddCustomStrategy(examples.Watch5Sec)
	bot.Execute()
}
